insert into esportes_estadio values (null, 'Maracanã' 'Rio de Janeiro', '82.238');
insert into esportes_estadio values (null, 'Mineirão', 'Belo Horizonte', '75.783');
insert into esportes_estadio values (null, 'Morumbi', 'São Paulo', '72.809');
insert into esportes_estadio values (null, 'Mangueirão', 'Belém', '69.985');
insert into esportes_estadio values (null, 'Castelão', 'Fortaleza', '66.100');
insert into esportes_estadio values (null, 'Arruda', 'Recife', '66.044 ');
insert into esportes_estadio values (null, 'Beira-Rio', 'Porto Alegre', ' 65.000');
insert into esportes_estadio values (null, 'Serra Dourada', 'Goiânia', ' 50.049');
insert into esportes_estadio values (null, 'Parque do Sabiá', 'Uberlândia', '50.000');
insert into esportes_estadio values (null, 'Engenhão', 'Rio de Janeiro', '46.931');